# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: cd myapp && go mod vendor && go build -v .
      
    - name: TestCeleritas
      run: cd celeritas && go test -v ./...
    
    - name: TestMyApp
      run: cd myapp/data && go test -v ./...
      
    - name: TestIntegration
      run: cd myapp/data && go test -v ./... --tags integration --count=1
