# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: BuildCLI
      run: go build -v ./celeritas/cmd/cli
      
    - name: BuildCeleritas
      run: go build -v ./celeritas
      
    - name: BuildMyApp
      run: go build -v ./myapp

    - name: TestRender
      run: go test -v ./celeritas/render
    
    - name: TestSession
      run: go test -v ./celeritas/session
      
    - name: TestDataModels
      run: go test -v ./myapp/data
      
    - name: TestDataIntegration
      run: go test -v ./myapp/data --tags integration --count=1
